apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gm1s2pq3t-nodejs
  janus-idp.io/tekton: gm1s2pq3t-nodejs
  backstage.io/kubernetes-id: gm1s2pq3t-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: gm1s2pq3t-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
