apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gm1s2pq3t-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gm1s2pq3t-nodejs 
  name: gm1s2pq3t-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: gm1s2pq3t-nodejs 
